// Dimension definitions for the 500+ bulk-testcase generator.
//
// Goal: programmatically author 500+ valid, varied testcases on the box via
// the REST create-lifecycle (POST /v2/tests/cells → subscribers → user-plane
// → power-cycle → mobility → settings), then validate every one of them via
// the API and a sampled subset via the UI.
//
// Each entry here describes one combinatorial slice of the (RAT × band ×
// bandwidth × duplex × UE-count × traffic) space. At generation time we
// fetch band-info from the live box, intersect each spec with the actual
// band/duplex/bandwidth combos the box supports, then materialise variants
// as concrete `BulkTestCaseSpec` objects.

export type RAT = 'LTE' | 'NR-SA' | 'NR-NSA' | 'NB-IoT';

/** A single "slice" of the matrix — covers a band-set within one RAT plus
 *  the variation knobs to multiply against it. */
export interface MatrixSlice {
  /** RAT family for this slice (drives cellType + ARFCN naming + sims). */
  rat: RAT;
  /** Bands to include from this RAT (must exist in the box's band-info). */
  bands: readonly string[];
  /** Bandwidths to attempt — at generation time we intersect with the
   *  band's allowed bandwidths from the box's band-info. */
  bandwidths: readonly number[];
  /** Subscriber counts to vary. */
  ueCounts: readonly number[];
  /** Antenna config DL×UL to vary. Each entry is `[dl, ul]`. */
  antennas: ReadonlyArray<readonly [number, number]>;
  /** User-plane traffic variant. `no_data` = no PDU traffic; `iperf-both` =
   *  iperf bidirectional; `iperf-dl` = DL-only iperf. The generator maps
   *  these to box-valid `dataType`/`dataDirection` pairs. */
  dataTypes: readonly ('no_data' | 'iperf-both' | 'iperf-dl')[];
  /** Soft cap so a single slice can't dominate the total. */
  maxVariants?: number;
}

// Defaults aimed at ~500 total variants once intersected with what the box
// actually supports. Tweak the per-slice numbers if a real lab returns a
// narrower set.
export const SLICES: readonly MatrixSlice[] = [
  // LTE — broadest coverage by far (most common deployment scenario).
  // LTE on this box requires ul antenna == 1, so the only ant variants are
  // 1×1, 2×1, 4×1. Matrix:
  //   12 bands × 4 bw × 4 ue × 3 ant × 3 traffic = 1728 raw, capped at 480.
  {
    rat: 'LTE',
    bands: ['1', '2', '3', '5', '7', '8', '13', '20', '25', '28', '41', '66'],
    bandwidths: [5, 10, 15, 20],
    ueCounts: [1, 2, 4, 8],
    antennas: [[1, 1], [2, 1], [4, 1]],
    dataTypes: ['no_data', 'iperf-both', 'iperf-dl'],
    maxVariants: 480,
  },
  // NR-SA — narrower but still meaningful coverage.
  // 8 bands × 3 bw × 3 ue × 2 ant × 2 traffic = 288 raw, capped at 60.
  {
    rat: 'NR-SA',
    bands: ['n2', 'n7', 'n28', 'n41', 'n66', 'n77', 'n78', 'n79'],
    bandwidths: [20, 40, 100],
    ueCounts: [1, 4, 16],
    antennas: [[2, 2], [4, 2]],
    dataTypes: ['no_data', 'iperf-dl'],
    maxVariants: 60,
  },
  // NR-NSA — small targeted set.
  {
    rat: 'NR-NSA',
    bands: ['n7', 'n41', 'n78'],
    bandwidths: [20, 40, 100],
    ueCounts: [1, 4],
    antennas: [[2, 2]],
    dataTypes: ['no_data'],
    maxVariants: 18,
  },
  // NB-IoT — tiny but covers the IoT path.
  {
    rat: 'NB-IoT',
    bands: ['8', '20'],
    bandwidths: [5],
    ueCounts: [1, 2],
    antennas: [[1, 1]],
    dataTypes: ['no_data'],
    maxVariants: 4,
  },
];

/** Concrete variant ready to feed the create-lifecycle. Generated by
 *  `expandSlices()` after intersecting with live band-info. */
export interface BulkTestCaseSpec {
  /** Deterministic id like "bulk-lte-3-bw20-ue2-ant2x2-dl_ul-001". */
  id: string;
  /** Human-readable name pushed to the box (used as the test-case name). */
  name: string;
  rat: RAT;
  band: string;
  bandwidth: number;
  duplexMode: 'FDD' | 'TDD';
  /** EARFCN (LTE) or NRARFCN (NR) values from band-info. */
  earfcnDl: number;
  earfcnUl?: number;          // LTE only
  nrarfcnSsb?: number;        // NR only
  scs?: number;               // NR only
  ueCount: number;
  antennas: { dl: number; ul: number };
  dataType: 'no_data' | 'iperf-both' | 'iperf-dl';
  /** Slice/RAT for grouped reporting. */
  category: 'bulk-lte' | 'bulk-nr-sa' | 'bulk-nr-nsa' | 'bulk-nbiot';
}

/** Naming prefix: every generated testcase carries this so cleanup is a
 *  one-shot search-and-delete. Also surfaced as a user_tag for filtering. */
export const BULK_NAME_PREFIX = 'qa-bulk';
export const BULK_TAG = 'qa-bulk';

/** Map RAT → category bucket for reporting. */
export function categoryOf(rat: RAT): BulkTestCaseSpec['category'] {
  switch (rat) {
    case 'LTE':    return 'bulk-lte';
    case 'NR-SA':  return 'bulk-nr-sa';
    case 'NR-NSA': return 'bulk-nr-nsa';
    case 'NB-IoT': return 'bulk-nbiot';
  }
}

/** Stable id-shaped name from a spec (lowercase, hyphen-safe). */
export function specToId(rat: RAT, band: string, bw: number, ueCount: number, antennas: { dl: number; ul: number }, dataType: string, seq: number): string {
  const ratSlug = rat.toLowerCase().replace(/[^a-z0-9]+/g, '');
  const bandSlug = band.toLowerCase().replace(/[^a-z0-9]+/g, '');
  const seqStr = String(seq).padStart(3, '0');
  return `${BULK_NAME_PREFIX}-${ratSlug}-${bandSlug}-bw${bw}-ue${ueCount}-ant${antennas.dl}x${antennas.ul}-${dataType}-${seqStr}`;
}
